name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    # Only deploy if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: |
          # Deploy directly without separate build step
          # Vercel will build and deploy in one command
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --debug
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
