name: Deploy Roadmap to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/planning/roadmap/ROADMAP-TIMELINE.html'
      - 'docs/planning/roadmap/roadmap-data.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/planning/roadmap
          publish_branch: gh-pages
          destination_dir: roadmap
          keep_files: true
