name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    # Only deploy if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Setup Vercel Project Link
        run: |
          # Create .vercel directory and project.json FIRST
          mkdir -p .vercel
          echo "{\"projectId\":\"${VERCEL_PROJECT_ID}\",\"orgId\":\"${VERCEL_ORG_ID}\"}" > .vercel/project.json

          # Verify the file was created (values will be masked but structure is visible)
          echo "✓ Created .vercel/project.json"
          ls -la .vercel/

          # Verify environment variables are set (for debugging)
          echo "VERCEL_PROJECT_ID is set: $([ -n "$VERCEL_PROJECT_ID" ] && echo 'YES' || echo 'NO')"
          echo "VERCEL_ORG_ID is set: $([ -n "$VERCEL_ORG_ID" ] && echo 'YES' || echo 'NO')"

          # Now try to pull additional environment information
          echo "Attempting to pull Vercel environment information..."
          if vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}; then
            echo "✓ Successfully pulled Vercel environment"
          else
            echo "⚠ Could not pull environment, using vercel.json configuration"
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --debug
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --debug
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
