name: Deploy Roadmap to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/planning/roadmap/ROADMAP-TIMELINE.html'
      - 'docs/planning/roadmap/roadmap-data.json'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/planning/roadmap
          publish_branch: gh-pages
          destination_dir: roadmap
          keep_files: true
          force_orphan: false
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy roadmap to GitHub Pages'
